### ISSUE TITLE
heads up

### ISSUE THREAD

**Issue by colemickens** [ImTheSquid/gst-webrtcredux#6]
Just came across this repo incidentally. Thought you might want to know about these if you don't already:

* https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/tree/main/net/webrtc
* https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/932

**Comment by Dreaming-Codes** [comment]
We already know it but unfortunately it does not work in our use case. In fact we are trying to stream to discord servers that use a non-standard implementation. So we could not get a working stream even directly with webrtcbin so we cannot use it.
Also this is a completely different project, it is not a wrapper for webrtcbin but instead we use [webrtc-rs](https://github.com/webrtc-rs/webrtc) to handle the stream.

**Comment by colemickens** [comment]
Nice, I'll definitely be keeping an eye on this then. Thanks for the explanation!
